---
title: "Testing"
author: "Quinn White"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```


```{r}

source('GET_VARS.R')

files <- dir(here("ballet_990_released_20230208"),
              full.names = TRUE)

all_sched_d <- map_df(files, ~get_df(
  filename = .x, 
  schedule = 'd'))


add_vars <-c("/Return/ReturnData/IRS990ScheduleD/BoardDesignatedBalanceEOYPct",
                 "/Return/ReturnData/IRS990ScheduleD/PrmnntEndowmentBalanceEOYPct",
                 "/Return/ReturnData/IRS990ScheduleD/TermEndowmentBalanceEOYPct",
                 "/Return/ReturnData/IRS990ScheduleD/EndowmentsHeldUnrelatedOrgInd",
                 "/Return/ReturnData/IRS990ScheduleD/EndowmentsHeldRelatedOrgInd")
  
  
  
# clean paths to names
path_to_name <- tibble(path = all_sched_d) %>%
  filter(grepl("CY|CYM", path) | path %in% add_vars) %>%
  # rename to CM* using the same formatting as we have throughout the project
  mutate(name = gsub("EndwmtFundGrp/|inus|Yr", "", path),
         name = gsub('.*./', '', name))
  

all_sched_d %>%
    rename_with(~gsub("/Return/ReturnData/IRS990ScheduleD/", "", .)) %>%
  glimpse()

  

endowment <- map_df(files, ~get_df(variables = path_to_name$path, 
                      names = path_to_name$name,
                      filename = .x))



```

```{r,eval = FALSE}
# scratch


# get names of all schedule D variables present in any file
all_sched_d <- map(files, ~get_all_children(
  filename = .x, 
  xpath =  "//IRS990ScheduleD"))

all_sched_d <- all_sched_d %>% unlist() %>% unique()

```

