---
title: "test"
author: "Zhen Nie"
date: '`r Sys.Date()`'
output: pdf_document
---

```{r}
source("GET_VARS.R")
library(rmarkdown)
library(here)
library(tibble)
library(dplyr)
library(ggplot2)
library(viridis)
```

## Infrastructure

```{r}
make_table <- function(df, title = "", ...) {
  title <- paste0("<center><span style = 'font-size:160%;color:black'><b>",
                  title,
                  "</span></b><center>")
   as_tibble(df) %>%
    kbl(caption = title, ... ) %>%
    kable_material() %>%
    row_spec(row=0, background = "#43494C" , color = "white", bold = TRUE)
}
```

```{r,eval=FALSE}
schedule_d <- map_df(files, ~get_df(filename = .x , 
                              schedule = 'd')) %>%
  filter_ein()

schedule_d %>%
  # remove /Return/ReturnData/IRS990ScheduleD/ from columns since this is shared
  # across all columns
  rename_with(~gsub("/Return/ReturnData/IRS990ScheduleD/", "", .))
  
companies<-read.csv(here("data","companies.csv")) %>% select(organization_name, EIN) %>% mutate(EIN=as.character(EIN))

buildings<-schedule_d[,c(1,35,2,5,86,87,124,159,160)] %>% 
  left_join(companies, by = "EIN") %>% 
  rename_with(~gsub("/Return/ReturnData/IRS990ScheduleD/", "", .)) %>% 
  filter(!is.na(organization_name)) %>% 
  mutate(fiscal_year = as.numeric(as.character(fiscal_year)))

saveRDS(buildings, "data/buildings.RDS")
```

## Overall Visualizations
```{r}
ggplot(buildings, aes(x = fiscal_year, y = as.numeric(TotalBookValueLandBuildingsAmt), color = as.factor(name)))+
  theme_bw()+
  geom_line()+
  geom_point()+
  scale_color_viridis(discrete=TRUE, option="A")+
  theme(legend.key.size = unit(1, "mm"),
        legend.text = element_text(size = 2))+
  labs(x = "Fiscal Year",
       y = "Total Book Values of Land and Buildings",
       color = "Company Name")

```

```{r}
high <- buildings %>% 
  mutate(quantile = ntile(TotalBookValueLandBuildingsAmt, 12)) %>% 
  filter(quantile >= 9)

medium <- buildings %>% 
  mutate(quantile = ntile(TotalBookValueLandBuildingsAmt, 12)) %>% 
  filter(quantile > 4 & quantile < 9)

low <- buildings %>% 
  mutate(quantile = ntile(TotalBookValueLandBuildingsAmt, 12)) %>% 
  filter(quantile <= 4)
```


```{r}

  ggplot(high,aes(x = fiscal_year, y=as.numeric(TotalBookValueLandBuildingsAmt), color=name))+
    geom_line()+
    geom_point()+
    theme_bw()+
    scale_color_viridis(discrete=TRUE,begin=.2,end=.8,option="A")+
    labs(x = "Fiscal Year", y = "Total Book Value Land Buildings Amount (High)", 
         color = "Company Name")+
    theme(legend.key.size = unit(1, "mm"),
        legend.text = element_text(size = 2))

```

```{r}

ggplot(medium, aes(x = fiscal_year, 
                   y = as.numeric(as.character(TotalBookValueLandBuildingsAmt)), 
                   color = as.factor(name)))+
    geom_line()+
    geom_point()+
    theme_bw()+
    scale_color_viridis(discrete=TRUE,begin=.2,end=.8,option="A")+
    labs(x = "Fiscal Year", y = "Total Book Value Land Buildings Amount (Medium)", 
         color = "Company Name")+
    theme(legend.key.size = unit(1, "mm"),
        legend.text = element_text(size = 2))

```

```{r}

  ggplot(low, aes(x = (fiscal_year), y = as.numeric(as.character(TotalBookValueLandBuildingsAmt)), color = as.factor(name)))+
    geom_line()+
    geom_point()+
    theme_bw()+
    scale_color_viridis(discrete=TRUE,begin=.2,end=.8,option = "A")+
    labs(x = "Fiscal Year", y = "Total Book Value Land Buildings Amount (Low)", color = "Company Name")+
   theme(plot.title = element_text(size = 13, face = "bold", hjust = .5),
        axis.title = element_text(size = 8, face = "bold"),
        plot.subtitle = element_text(size = 5, face = "italic", hjust = .5),
        axis.text.x = element_text(size = 10, angle = 25),
        strip.text = element_text(face="bold",size = 5),
        legend.key.size = unit(1, 'mm'),
        legend.text = element_text(size=2))

```


```{r}
building_summary_state<-buildings %>% 
  group_by(state,fiscal_year) %>% 
  summarise(
    `Reporting companies number` = n(),
    Mean = mean(as.numeric(TotalBookValueLandBuildingsAmt), na.rm=TRUE),
    Median = median(as.numeric(TotalBookValueLandBuildingsAmt),na.rm=TRUE),
    Max = max(as.numeric(TotalBookValueLandBuildingsAmt),na.rm=TRUE),
    Min = min(as.numeric(TotalBookValueLandBuildingsAmt),na.rm=TRUE)
  ) 
building_summary_state
```

```{r}
building_summary<-buildings %>% 
  group_by(fiscal_year) %>% 
  summarise(
    `Reporting companies number` = n(),
    Mean = mean(as.numeric(TotalBookValueLandBuildingsAmt), na.rm=TRUE),
    Median = median(as.numeric(TotalBookValueLandBuildingsAmt),na.rm=TRUE),
    Max = max(as.numeric(TotalBookValueLandBuildingsAmt),na.rm=TRUE),
    Min = min(as.numeric(TotalBookValueLandBuildingsAmt),na.rm=TRUE)
  ) 
building_summary
```


```{r}
# ranking

data2014<-buildings %>% filter(fiscal_year==2014) %>% unique() %>% mutate(TotalBookValueLandBuildingsAmt = as.numeric(TotalBookValueLandBuildingsAmt))
data2015<-buildings %>% filter(fiscal_year==2015) %>% unique()%>% mutate(TotalBookValueLandBuildingsAmt = as.numeric(TotalBookValueLandBuildingsAmt))
data2016<-buildings %>% filter(fiscal_year==2016) %>% unique() %>% mutate(TotalBookValueLandBuildingsAmt = as.numeric(TotalBookValueLandBuildingsAmt))
data2017<-buildings %>% filter(fiscal_year==2017) %>% unique()%>% mutate(TotalBookValueLandBuildingsAmt = as.numeric(TotalBookValueLandBuildingsAmt)) 
data2018<-buildings %>% filter(fiscal_year==2018) %>% unique()%>% mutate(TotalBookValueLandBuildingsAmt = as.numeric(TotalBookValueLandBuildingsAmt))
data2019<-buildings %>% filter(fiscal_year==2019) %>% unique()%>% mutate(TotalBookValueLandBuildingsAmt = as.numeric(TotalBookValueLandBuildingsAmt))
data2020<-buildings %>% filter(fiscal_year==2020) %>% unique()%>% mutate(TotalBookValueLandBuildingsAmt = as.numeric(TotalBookValueLandBuildingsAmt))
data2021<-buildings %>% filter(fiscal_year==2021) %>% unique()%>% mutate(TotalBookValueLandBuildingsAmt = as.numeric(TotalBookValueLandBuildingsAmt))


data2014$rank = rank(-data2014$TotalBookValueLandBuildingsAmt)
data2015$rank = rank(-data2015$TotalBookValueLandBuildingsAmt)
data2016$rank = rank(-data2016$TotalBookValueLandBuildingsAmt)
data2017$rank = rank(-data2017$TotalBookValueLandBuildingsAmt)
data2018$rank = rank(-data2018$TotalBookValueLandBuildingsAmt)
data2019$rank = rank(-data2019$TotalBookValueLandBuildingsAmt)
data2020$rank = rank(-data2020$TotalBookValueLandBuildingsAmt)
data2021$rank = rank(-data2021$TotalBookValueLandBuildingsAmt)

rankings <- rbind(data2014,data2015,data2016,data2017,data2018,data2019,data2020,data2021)
```

```{r}
# ranking vis

ggplot(rankings %>% filter(fiscal_year!=2014&fiscal_year!=2021), aes(x = fiscal_year, y = rank, color = organization_name.x))+
  geom_line()+
  theme_bw()+
  theme(plot.title = element_text(size = 13, face = "bold", hjust = .5),
        axis.title = element_text(size = 12, face = "bold"),
        plot.subtitle = element_text(size = 5, face = "italic", hjust = .5),
        axis.text.x = element_text(size = 10, angle = 25),
        strip.text = element_text(face="bold",size = 5),
        legend.key.size = unit(1, 'mm'),
        legend.position = "none")+
  scale_color_viridis(discrete=TRUE,begin=.2,end=.8,option = "A")+
  scale_y_reverse()+
  labs(x = "Fiscal Year",
      y = "Ranking of Book Values",
      color = "Company Names") +
  geom_text(data = rankings %>% filter(fiscal_year != 2014 & fiscal_year != 2021) %>% group_by(organization_name.x) %>% slice_tail(n =1),aes(label = organization_name.x),size = 1.5, color = "black")
```
```{r}
# companies have a change in ranking larger than 10 
rankings <- rankings %>% 
  mutate(rank_change = abs(rank - lag(rank)))
```


```{r}
#filter out rank change > 20
larger20<-rankings%>%
  filter(rank_change >= 20) %>% 
  filter(fiscal_year != 2014 & fiscal_year != 2021) %>% 
  select(fiscal_year, EIN, organization_name.x,business_state_cd, rank, rank_change) %>% 
  ggplot(aes(x=fiscal_year, y = rank, color = organization_name.x))+
  geom_line()+
  geom_point()+
  theme_bw()+
  theme(plot.title = element_text(size = 13, face = "bold", hjust = .5),
        axis.title = element_text(size = 12, face = "bold"),
        plot.subtitle = element_text(size = 5, face = "italic", hjust = .5),
        axis.text.x = element_text(size = 10, angle = 25),
        strip.text = element_text(face="bold",size = 5),
        legend.position = "none")+
  scale_color_viridis(discrete=TRUE,begin=.2,end=.8,option = "A")+
  scale_y_reverse()+
  labs(x = "Fiscal Year",
      y = "Ranking of Book Values",
      color = "Company Names") +
  geom_text(data = rankings %>% 
              filter(fiscal_year != 2014 & fiscal_year != 2021) %>% 
              group_by(organization_name.x) %>% slice_tail(n =1),
            aes(label = organization_name.x),size = 1.5, color = "black"
            , fontface = "bold", color = "white", 
            fill = "black", label.padding = unit(0.4, "lines"), 
            show.legend = FALSE, geom = "label")
larger20
ggplotly(larger20)
```


## Percentage Change
```{r}
options(scipen = 999, digits = 3)
changes<-buildings %>% 
  group_by(name) %>% 
  mutate(change = (as.numeric(TotalBookValueLandBuildingsAmt) - lag(as.numeric(TotalBookValueLandBuildingsAmt))) / lag(as.numeric(TotalBookValueLandBuildingsAmt)) * 100) %>%
  mutate(change_abs = abs(change))
changes <- changes[,c(2,3,11,13,14,15,16,17)]

```
geom_text(data = changes %>% 
                    group_by(name) %>% 
                    slice_tail(n = 1), aes(label = name),
            nudge_x = 0.1, hjust = 0, vjust = -0.5,
            size = 2)
```{r}
# change overall
  ggplot(changes, aes(x = fiscal_year, y = change, color = as.factor(name)))+
    geom_point()+
    geom_line(stat = "identity")+
    theme_bw()+
    scale_color_viridis(discrete=TRUE,begin=.2,end=.8,option = "A")+
    labs(x = "Fiscal Year", y = "Total Book Value Land Buildings Amount",
         color = "Company Name")+
    theme(legend.key.size = unit(1, "mm"),
        legend.text = element_text(size = 2))
  

```

```{r}
smaller<-changes %>% 
  filter(change_abs <= 100) %>% 
  mutate(name = stringr::str_to_title(name)) %>% 
  unique()

bigger<-changes %>% 
  filter(change_abs > 100) %>% 
  mutate(name = stringr::str_to_title(name)) %>% 
  unique()
```

```{r}
#change smaller than 100%
ggplot(smaller %>% 
         filter(fiscal_year!=2014 & fiscal_year!=2021) %>% 
         filter(change != 0), aes(x = fiscal_year, 
                                                          y = change, 
                                                          color = as.factor(name)))+
    geom_point()+
    geom_line()+
    theme_bw()+
    scale_color_viridis(discrete=TRUE,begin=.2,end=.8,option = "A")+
    labs(x = "Fiscal Year", y = "Compnies with changes less than 100%",color = "Company Name")+
    theme(plot.title = element_text(size = 13, face = "bold", hjust = .5),
        axis.title = element_text(size = 12, face = "bold"),
        plot.subtitle = element_text(size = 5, face = "italic", hjust = .5),
        axis.text.x = element_text(size = 10, angle = 25),
        strip.text = element_text(face="bold",size = 5),
        legend.position = "none")+
  geom_text(data = smaller %>% filter(fiscal_year!=2014 & fiscal_year!=2021) %>% 
         filter(change != 0) %>% group_by(name) %>% slice_tail(n = 1), aes(label = name),
            hjust = -0.1, vjust = 0, size = 2 )+
  xlim(2015,2021)
```


```{r}
# changes larger than 100%

  ggplot(bigger, aes(x = (fiscal_year), y = change, color = as.factor(name)))+
    geom_point()+
    geom_line()+
    theme_bw()+
    scale_color_viridis(discrete=TRUE,begin=.2,end=.8,option = "A")+
    labs(x = "Fiscal Year", y = "Total Book Value Land Buildings Amount",color = "Company Name")+
    theme(plot.title = element_text(size = 13, face = "bold", hjust = .5),
        axis.title = element_text(size = 7, face = "bold"),
        plot.subtitle = element_text(size = 5, face = "italic", hjust = .5),
        axis.text.x = element_text(size = 7, angle = 25),
        strip.text = element_text(face="bold",size = 5),
        legend.key.size = unit(1, 'mm'),
        legend.text = element_text(size=4))+
  geom_text(data = bigger %>% group_by(name) %>% slice_tail(n = 1), aes(label = name),hjust = -0.1, vjust = 0, size = 2 )
  #ylim(-30000,15000)

```
```{r}
smaller %>% 
  select(name, fiscal_year, change) %>% 
  arrange(desc(change)) %>% 
  filter(change != 0) %>% 
  rename(
    `Fiscal Year` = fiscal_year,
    `Company Name` = name,
    `% Change` = change
  ) %>% 
  make_table(title = "Companies with % Change smaller than 1000")
```

```{r}
bigger %>% 
  select(name, fiscal_year, change) %>% 
  arrange(desc(change)) %>% 
  rename(
    `Fiscal Year` = fiscal_year,
    `Company Name` = name,
    `% Change` = change
  ) %>% 
  make_table(title = "Companies with % Change larger than 1000")

```

```{r}
data<-buildings %>% select(fiscal_year, organization_name.x, TotalBookValueLandBuildingsAmt) %>%
  rename(name = organization_name.x)

# changes equal to 0
changes %>% 
  filter(change == 0) %>%
  select(name, fiscal_year) %>% 
  left_join(data, by = c(name, fiscal_year)) %>% 
  rename(
    `Fiscal Year` = fiscal_year,
    `Company Name` = name
  ) %>% 
  unique() %>% 
  make_table(title = "Companies with no % Change in Building and Land")
```

```{r}
negative <-changes %>% 
  filter(change <0)


positive <-changes %>% 
  filter(change >0)
```

```{r}
# negative changes
  ggplot(negative, aes(x = (fiscal_year), y = change, color = as.factor(organization_name)))+
    geom_point()+
    geom_line(stat = "identity")+
    theme_bw()+
    scale_color_viridis(discrete=TRUE,begin=.2,end=.8,option = "A")+
    labs(x = "Fiscal Year", y = "Companies with Negative % Change in Book Value",
         color = "Company Name")+
    theme(plot.title = element_text(size = 13, face = "bold", hjust = .5),
        axis.title = element_text(size = 7, face = "bold"),
        plot.subtitle = element_text(size = 5, face = "italic", hjust = .5),
        axis.text.x = element_text(size = 7, angle = 25),
        strip.text = element_text(face="bold",size = 5),
        legend.key.size = unit(1, 'mm'),
        legend.text = element_text(size=2))+
  geom_text(aes(label = name),
            nudge_x = 0.1, hjust = 0, vjust = -0.5,
            size = 2)
```

```{r}

  ggplot(positive,aes(x = (fiscal_year), y = change, color = as.factor(organization_name)))+
    geom_point()+
    geom_line()+
    theme_bw()+
    scale_color_viridis(discrete=TRUE,begin=.2,end=.8,option = "A")+
    labs(x = "Fiscal Year", y = "Companies with Postivie Change in Book Values", color = "Company Name")+
   theme(plot.title = element_text(size = 13, face = "bold", hjust = .5),
        axis.title = element_text(size = 8, face = "bold"),
        plot.subtitle = element_text(size = 5, face = "italic", hjust = .5),
        axis.text.x = element_text(size = 10, angle = 25),
        strip.text = element_text(face="bold",size = 5),
        legend.key.size = unit(1, 'mm'),
        legend.text = element_text(size=2))+
  geom_text(data = positive %>% group_by(organization_name) %>% slice_tail(n=1), aes(label = organization_name),
            nudge_x = 0.1, hjust = 0, vjust = -0.5,
            size = 2)+
  xlim(2015,2022)
```
```{r}
positive %>% 
  select(fiscal_year, organization_name) %>% 
  unique()
```

```{r}
changes %>% 
  filter(change != Inf) %>% 
  group_by(fiscal_year) %>% 
  summarise(
    Mean = mean(change, na.rm=TRUE),
    Median = median(change,na.rm=TRUE),
    Max = max(change,na.rm=TRUE),
    Min = min(change,na.rm=TRUE)
  ) %>% 
  make_table(title = "Summary of % Changes in Book Values")
```

```{r}
changes %>% 
  filter(change > 100) %>% 
  select(organization_name, fiscal_year, change) %>% 
  arrange(desc(change))
```

```{r}
changes %>% 
  arrange(desc(change)) %>% 
  filter(change != Inf) %>% 
  na.omit() %>% 
  filter(change>100) %>% 
  select(fiscal_year, organization_name.x,change) %>% 
  mutate(`Fiscal Year` = fiscal_year,
         `Company Name` = organization_name.x,
         `% Change` = change)
```

```{r}
changes %>% 
  arrange(desc(change)) %>% 
  na.omit() %>% 
  filter(change<100) %>% 
  select(fiscal_year, organization_name,change)
```

## Regional Analysis

```{r}
state<-readRDS(here("data","ein_to_state_update.RDS"))
buildings<-buildings %>% 
  left_join(state, by = "EIN")
```


```{r}
# sum 
buildings %>% 
  filter(fiscal_year != 2014 & fiscal_year != 2021) %>% 
  group_by(state, fiscal_year) %>% 
  summarise(
    mean = mean(as.numeric(TotalBookValueLandBuildingsAmt), na.rm=TRUE),
    median = median(as.numeric(TotalBookValueLandBuildingsAmt), na.rm=TRUE),
    max = max(as.numeric(TotalBookValueLandBuildingsAmt), na.rm=TRUE),
    min = min(as.numeric(TotalBookValueLandBuildingsAmt), na.rm=TRUE),
    sum = sum(as.numeric(TotalBookValueLandBuildingsAmt), na.rm=TRUE)) %>% 
  arrange(desc(sum)) %>% 
  ggplot(aes(x = fiscal_year, y = sum, color = state))+
  geom_point()+
  geom_line()+
  theme_bw()+
  scale_color_viridis(discrete = TRUE, option="A")+
  labs(x = "Fiscal Year", y = "Sum of Total Book Values by State", color = "State")+
 theme(plot.title = element_text(size = 13, face = "bold", hjust = .5),
        axis.title = element_text(size = 12, face = "bold"),
        plot.subtitle = element_text(size = 5, face = "italic", hjust = .5),
        axis.text.x = element_text(size = 10, angle = 25),
        strip.text = element_text(face="bold",size = 5),
        legend.key.size = unit(1, 'mm'),
        legend.text = element_text(size=7)) +
  geom_text(aes(label = state),
            nudge_x = 0.1, hjust = 0, vjust = -0.5,
            size = 2)
```
```{r}
# company reporting
buildings %>% 
  filter(fiscal_year != 2014 & fiscal_year != 2021) %>% 
  group_by(state, fiscal_year) %>% 
  summarise(
    Number = n()
  ) %>% 
  unique() %>% 
  ggplot(aes(x = fiscal_year, y = Number, color = state))+
  geom_line()+
  geom_point()+
  theme_bw()+
  scale_color_viridis(discrete = TRUE, option="A")+
  labs(x = "Fiscal Year", 
       y = "Number",
       color = "State",
       title = "Companies reporting Total Building and Land Book Values")+
  theme(plot.title = element_text(size = 13, face = "bold", hjust = .5),
        axis.title = element_text(size = 12, face = "bold"),
        plot.subtitle = element_text(size = 5, face = "italic", hjust = .5),
        axis.text.x = element_text(size = 10, angle = 25),
        strip.text = element_text(face="bold",size = 5),
        legend.key.size = unit(1, 'mm'),
        legend.text = element_text(size=7))+
  geom_text(data = buildings %>% 
                    filter(fiscal_year != 2014 & fiscal_year != 2021) %>% 
                    group_by(state, fiscal_year) %>% 
                    summarise(
                      Number = n()
                    ) %>% 
                    unique() %>% group_by(state) %>% slice_tail(n = 1), aes(label = state),
            nudge_x = 0.1, hjust = 0, vjust = -0.5,
            size = 2)
```
```{r}
#Companies number in 2020
buildings %>% 
  filter(fiscal_year != 2014 & fiscal_year != 2021) %>% 
  group_by(state, fiscal_year) %>% 
  summarise(
    Number = n()
  ) %>% 
  unique() %>% filter(fiscal_year == 2020) %>% arrange(desc(Number))
```


```{r}
# rank of regions

rank2014<-data2014 %>% 
  group_by(state) %>% 
  summarise(sum = sum(as.numeric(TotalBookValueLandBuildingsAmt))) %>% 
  mutate(Year = 2014)
rank2015<-data2015 %>% 
  group_by(state) %>% 
  summarise(sum = sum(as.numeric(TotalBookValueLandBuildingsAmt)))%>% 
  mutate(Year = 2015)
rank2016<-data2016 %>% 
  group_by(state) %>% 
  summarise(sum = sum(as.numeric(TotalBookValueLandBuildingsAmt)))%>% 
  mutate(Year = 2016)
rank2017<-data2017 %>% 
  group_by(state) %>% 
  summarise(sum = sum(as.numeric(TotalBookValueLandBuildingsAmt)))%>% 
  mutate(Year = 2017)
rank2018<-data2018 %>% 
  group_by(state) %>% 
  summarise(sum = sum(as.numeric(TotalBookValueLandBuildingsAmt)))%>% 
  mutate(Year = 2018)
rank2019<-data2019 %>% 
  group_by(state) %>% 
  summarise(sum = sum(as.numeric(TotalBookValueLandBuildingsAmt)))%>% 
  mutate(Year = 2019)
rank2020<-data2020 %>% 
  group_by(state) %>% 
  summarise(sum = sum(as.numeric(TotalBookValueLandBuildingsAmt)))%>% 
  mutate(Year = 2020)
rank2021<-data2021 %>% 
  group_by(state) %>% 
  summarise(sum = sum(as.numeric(TotalBookValueLandBuildingsAmt)))%>% 
  mutate(Year = 2021)

rank2014$rank = rank(-rank2014$sum)
rank2015$rank = rank(-rank2015$sum)
rank2016$rank = rank(-rank2016$sum)
rank2017$rank = rank(-rank2017$sum)
rank2018$rank = rank(-rank2018$sum)
rank2019$rank = rank(-rank2019$sum)
rank2020$rank = rank(-rank2020$sum)
rank2021$rank = rank(-rank2021$sum)

ranking_state<-rbind(rank2014,rank2015,rank2016,rank2017,rank2018,rank2019,rank2020,rank2021)  
  
```

```{r}
# rank by absolute sum 
ggplot(ranking_state, aes(x = Year, y = sum, color = state))+
  #geom_point()+
  geom_line()+
  theme_bw()+
  scale_color_viridis(discrete=TRUE, option="A")+
  labs(x = "Fiscal Year", 
       y = "Sum",
       color = "State",
       title = "Sum of Book Values by State")+
  theme(plot.title = element_text(size = 13, face = "bold", hjust = .5),
        axis.title = element_text(size = 12, face = "bold"),
        plot.subtitle = element_text(size = 5, face = "italic", hjust = .5),
        axis.text.x = element_text(size = 10, angle = 25),
        strip.text = element_text(face="bold",size = 5),
        legend.key.size = unit(1, 'mm'),
        legend.text = element_text(size=4))+
  geom_text(data = ranking_state %>% group_by(state) %>% slice_tail(n = 1), aes(label = state),
            nudge_x = 0.1, hjust = 0, vjust = -0.5, size = 3)
  
```

```{r}
ggplot(ranking_state, aes(x = Year, y = rank, color = state))+
  #geom_point()+
  geom_line()+
  theme_bw()+
  scale_color_viridis(discrete=TRUE, option="A")+
  labs(x = "Fiscal Year", 
       y = "Rank",
       color = "State",
       title = "Rank of Total Building and Land Book Values by State")+
  theme(plot.title = element_text(size = 13, face = "bold", hjust = .5),
        axis.title = element_text(size = 12, face = "bold"),
        plot.subtitle = element_text(size = 5, face = "italic", hjust = .5),
        axis.text.x = element_text(size = 10, angle = 25),
        strip.text = element_text(face="bold",size = 5),
        legend.key.size = unit(1, 'mm'),
        legend.text = element_text(size=4))+
  scale_y_reverse()+
  geom_text(data = ranking_state %>% group_by(state) %>% slice_tail(n = 1), aes(label = state),
            nudge_x = 0.1, hjust = 0, vjust = -0.5, size = 3)
```



