---
title: "Cross Referencing Endowment Values"
author: "Quinn White"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    df_print: paged
    code_folding: hide
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "./output_html")})
---


```{css, echo = FALSE}

/* expand content to screenwidth rather than cutting it off */
#content{
max-width:2300px;
}

```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE)
library(tidyverse)
library(kableExtra)

```

```{r}

endowment_data <- read_rds("./data/endowment_filter_data_990.RDS") 

companies_to_ein <- read_csv("./data/companies.csv") %>%
  mutate(EIN = as.character(ein))

```


```{r}


# make kable table with consistent formatting
make_table <- function(df, title = "", ...) {
  title <- paste0("<center><span style = 'font-size:150%;color:black'><b>",
                  title,
                  "</span></b><center>")
   as_tibble(df) %>%
    kbl(caption = title, ... ) %>%
    kable_material() %>%
    row_spec(row=0, background = "#43494C" , color = "white", bold = TRUE)
}


```


```{r, include=FALSE,eval=FALSE}

# testing / function development


endowment_data %>%
  group_by(EIN) %>%
  summarize(number_observations = sum(!is.na(CYBeginningYearBalanceAmt))) %>%
  group_by(number_observations) %>%
  summarize(n=n()) %>%
  ggplot(aes(x = number_observations, y =n ))+
  geom_bar(stat="identity") +
  labs(y = "Number of Companies",
       x = "Number of Observations where\nCYBeginningYearBalanceAmt was Not Missing",
       title ="Missingness for CYBeginningYearBalanceAmt") +
  theme_bw() +
  theme(plot.title = element_text(face = "bold", hjust = .5)) 


# eins that have at least one observation of the variable of interest
eins_with_variable <- endowment_data %>%
  group_by(EIN) %>%
  summarize(number_observations = sum(!is.na(CYBeginningYearBalanceAmt))) %>%
  filter(number_observations != 0) %>%
  pull(EIN)
  

base_name <- "BeginningYearBalanceAmt"
var <- paste0("CY", base_name)
vars <- paste0("CYM", c( 1:4), base_name)

crossref <- endowment_data %>%
  filter(EIN %in% eins_with_variable) %>%
  select(EIN, fiscal_year, contains(base_name)) %>%
  group_by(EIN) %>%
  arrange(fiscal_year) %>%
  # lag corresponds to how far back the current year comparison should be
  # vars contains the CM* variables that represent reporting for years back
  # compare these CM* variables to the lagged current year variables
  mutate(
    difference_in_reported_year1 =  !!sym(vars[1]) - 
      lag(!!sym(var), n =1),
    difference_in_reported_year2 =  !!sym(vars[2]) - 
      lag(!!sym(var), n =2),
    difference_in_reported_year3 =  !!sym(vars[3]) - 
      lag(!!sym(var), n =3),
     difference_in_reported_year4 =  !!sym(vars[4]) - 
      lag(!!sym(var), n =4)
    ) 




```


```{r,eval=FALSE}

eins_with_variable <- endowment_data %>%
  group_by(EIN) %>%
  summarize(number_observations = sum(!is.na(CYBeginningYearBalanceAmt))) %>%
  filter(number_observations != 0) %>%
  pull(EIN)
  

base_name <- "BeginningYearBalanceAmt"
var <- paste0("CY", base_name)
vars <- paste0("CYM", c( 1:4), base_name)

crossref <- endowment_data %>%
  filter(EIN %in% eins_with_variable) %>%
  select(EIN, fiscal_year, contains(base_name)) %>%
  group_by(EIN) %>%
  arrange(fiscal_year) %>%
  mutate(fiscal_year = as.numeric(paste(fiscal_year))) %>%
  mutate(difference_years = fiscal_year - lag(fiscal_year, n =1)) %>%
  filter(difference_years>1)

# the goal here is to create a row for each fiscal year, with NAs if 
# there are no observations for that year
# this is needed so that we have consecutive years, which is important
# for substraction using lag() to work correctly

 endowment_data %>%
  filter(EIN %in% eins_with_variable) %>%
  select(EIN, fiscal_year, contains(base_name)) %>%
   pivot_wider(names_from = fiscal_year, 
               names_prefix = "fiscalyear",
               values_from=CYBeginningYearBalanceAmt) %>%
   pivot_longer( cols= contains("fiscalyear"),
                 values_to ="CYBeginningYearBalanceAmt") %>%
   View()
   
 
 
 
```



```{r}

plot_missing <- function(variable) {
  
  endowment_data %>%
    group_by(EIN) %>%
    summarize(number_observations = sum(!is.na(!!sym(variable)))) %>%
    group_by(number_observations) %>%
    summarize(n=n()) %>%
    ggplot(aes(x = number_observations, y =n ))+
    geom_bar(stat="identity") +
    labs(y = "Number of Companies",
         x = paste0("Number of Observations where\n",
         variable, " was Not Missing"),
         title =paste0("Missingness for ", variable)) +
    theme_bw() +
    theme(plot.title = element_text(face = "bold", hjust = .5)) 

}


# note -- only works if years are consecutive 

check_variable <- function(variable_name,
                           data) {
  
  
  base_name <- variable_name
  var <- paste0("CY", base_name)
  vars <- paste0("CYM", c( 1:4), base_name)
  
  plt <- plot_missing(var)
  
  print(plt)
  
  eins_with_variable <- data %>%
    group_by(EIN) %>%
    summarize(number_observations = sum(!is.na(!!sym(var)))) %>%
    filter(number_observations != 0) %>%
    pull(EIN)
  
  
  # the goal here is to create a row for each fiscal year, with NAs if 
  # there are no observations for that year
  # this is needed so that we have consecutive years, which is important
  # for substraction using lag() to work correctly

 data <- data %>%
  filter(EIN %in% eins_with_variable) %>%
  select(EIN, fiscal_year, contains(base_name)) %>%
   pivot_wider(names_from = fiscal_year, 
             #  names_prefix = "fiscalyear",
               values_from=contains(base_name)) %>%
   pivot_longer(cols = contains(base_name),
                names_to = "variable_year") %>%
   separate(variable_year, sep = "_", into = c("variable_name", "fiscal_year")) %>%
   pivot_wider(names_from = variable_name, values_from = value) %>%
   mutate(fiscal_year = as.factor(as.numeric(fiscal_year)))
 

  
  crossref <- data %>%
    group_by(EIN) %>%
    arrange(fiscal_year) %>%
    # lag corresponds to how far back the current year comparison should be
    # vars contains the CM* variables that represent reporting for years back
    # compare these CM* variables to the lagged current year variables
    mutate(
      difference_in_reported_year1 =  !!sym(vars[1]) - 
        lag(!!sym(var), n =1),
      difference_in_reported_year2 =  !!sym(vars[2]) - 
        lag(!!sym(var), n =2),
      difference_in_reported_year3 =  !!sym(vars[3]) - 
        lag(!!sym(var), n =3),
       difference_in_reported_year4 =  !!sym(vars[4]) - 
        lag(!!sym(var), n =4)
      )  %>%
    ungroup()

}


```


# Cross Referencing Beginning Year Balance Amount

## Comparison Across Years

As we might expect, we see that a higher proportion had no difference between the cross referenced reports for more recent years. That is, reporting tended to be more accurate for most recent years.


```{r}

crossref <- check_variable("BeginningYearBalanceAmt", data = endowment_data)


# stacked chart, note we can't see how nonzero counts are changing 
# relative to the total counts

crossref %>%
  select(EIN, contains("difference")) %>%
  pivot_longer(cols = contains("difference")) %>%
  filter(!is.na(value)) %>%
  group_by(name)  %>%
  summarize(zero = sum(ifelse(value == 0, 1,0)),
            nonzero = sum(ifelse(value == 0, 0,1))) %>%
  pivot_longer(cols = c(zero, nonzero),
               names_to = "source",
               values_to = "count") %>%
  mutate(name = gsub("difference_in_reported_year", "", name)) %>%
  ggplot(aes(x=name, y = count, fill = source)) +
  geom_bar(stat ="identity", position = "stack") +
  geom_label(aes(label = round(count,2), y = count),
             position = "stack",
             size = 2.6,
             label.padding = unit(.1, "lines"),
             show.legend = FALSE) +
  labs(title = "EINs with Zero and Nonzero Difference\nBetween Cross Referenced Reports",
       subtitle = "By Year",
       x = "Year",
       y = "Count") +
  theme_bw() +
  theme(plot.title = element_text(size = 16, hjust = .5, face="bold"),
        plot.subtitle = element_text(hjust = .5, face="italic"),
        axis.text.x = element_text(size = 13),
        axis.title = element_text(size = 16, face = "bold"))


```

```{r}


# plot fraction where there was no difference betewen 
# the reports by year
crossref %>% 
  select(EIN, contains("difference")) %>%
  pivot_longer(cols = contains("difference")) %>%
  filter(!is.na(value)) %>%
  group_by(name)  %>%
  summarize(number_zeros = sum(ifelse(value == 0, 1,0)),
            total_reports = n(),
            fraction = number_zeros / total_reports) %>%
  mutate(name = gsub("difference_in_reported_year", "", name)) %>%
  ggplot(aes(x=name, y = fraction)) +
  geom_bar(stat ="identity", fill = "#234A77") +
  geom_label(aes(label = round(fraction,2))) +
  labs(title = "Fraction of EINs with No Difference\nBetween Cross Referenced Reports",
       subtitle = "By Year",
       x = "Year",
       y = "Fraction with No Difference") +
  theme_bw() +
  theme(plot.title = element_text(hjust = .5, face="bold"),
        plot.subtitle = element_text(hjust = .5, face="italic"))


```

We also see we have fewer total counts of non-missing reports as we go further back in time.

```{r}

# plot counts
crossref %>%
  select(EIN, contains("difference")) %>%
  pivot_longer(cols = contains("difference")) %>%
  filter(!is.na(value)) %>%
  group_by(name)  %>%
  summarize(zero = sum(ifelse(value == 0, 1,0)),
            nonzero = sum(ifelse(value == 0, 0,1))) %>%
  pivot_longer(cols = c(zero, nonzero),
               names_to = "source",
               values_to = "count") %>%
  mutate(name = gsub("difference_in_reported_year", "", name)) %>%
  ggplot(aes(x=name, y = count, fill = source)) +
  geom_bar(stat ="identity", position = "stack") +
  geom_label(aes(label = round(count,2), y = count),
             position = "stack",
             size = 2.6,
             label.padding = unit(.1, "lines"),
             show.legend = FALSE) +
  labs(title = "EINs with Zero and Nonzero Difference\nBetween Cross Referenced Reports",
       subtitle = "By Year",
       x = "Year",
       y = "Count") +
  theme_bw() +
  theme(plot.title = element_text(size = 16, hjust = .5, face="bold"),
        plot.subtitle = element_text(hjust = .5, face="italic"),
        axis.text.x = element_text(size = 13),
        axis.title = element_text(size = 16, face = "bold"))


```


```{r}

"What They Reported as CY Minus X Years - What They Reported at The Time"


crossref %>%
  pivot_longer(cols = contains("difference")) %>%
  select(EIN, fiscal_year, name, value) %>%
  filter(value > 0) %>%
  left_join(companies_to_ein, by = c("EIN" = "EIN")) %>%
  mutate(year = substr(name, nchar(name), nchar(name)),
         year = paste0("Comparing Current Year Minus ",
                       year)) %>%
  arrange(organization_name) %>%
  select(`Organization Name` = organization_name,
         Year = year, 
         `Fiscal Year` = fiscal_year,
         `Recent Value - Value <br> Reported Previously` = value) %>%
  make_table(title = "Comparing Values Reported in More Recent Reports<br>to Those Previously Reported",
             digits = 3, 
             format.args = list(
               big.mark = ",",
               scientific = FALSE))  %>%
  scroll_box(height = "450px")





crossref %>%
  pivot_longer(cols = contains("difference")) %>%
  select(EIN, fiscal_year, name, value) %>%
  # filter(value > 0) %>%
  left_join(companies_to_ein, by = c("EIN" = "EIN")) %>%
  mutate(year = substr(name, nchar(name), nchar(name)),
         year = paste0("Comparing Current Year Minus ",
                       year)) %>%
  arrange(organization_name) %>% View()

```


```{r,eval=FALSE}

crossref %>% 
  select(EIN, contains("difference")) %>%
  pivot_longer(cols = contains("difference")) %>%
  group_by(name) %>%
  mutate(count_na = sum(is.na(value)),
            count_not_na = sum(!is.na(value))) %>%
  ungroup() %>%
  ggplot(aes(x = value)) +
 # geom_boxplot() +
  geom_histogram(bins = 50)

crossref %>% 
  select(EIN, contains("difference")) %>%
  pivot_longer(cols = contains("difference")) %>%
  group_by(name) %>%
  mutate(count_na = sum(is.na(value)),
            count_not_na = sum(!is.na(value))) %>%
  ungroup() %>%
  ggplot(aes(x = name, y=value)) +
  geom_boxplot() +
  geom_jitter(alpha = .5, height = 0, width = .01)

crossref %>% 
  select(EIN, contains("difference")) %>%
  pivot_longer(cols = contains("difference")) %>%
  group_by(name) %>%
  mutate(count_na = sum(is.na(value)),
            count_not_na = sum(!is.na(value))) %>%
  ungroup() %>%
  ggplot(aes(x = name, y = value)) +
 # geom_boxplot() +
  geom_density()



  geom_histogram() +
  facet_wrap(~name) +
  scale_x_log10()


```

