---
title: "Testing"
author: "Quinn White"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```


```{r}
d 
source('GET_VARS.R')

files <- dir(here("ballet_990_released_20230208"),
              full.names = TRUE)

all_sched_d <- map_df(files, ~get_df(
  filename = .x, 
  schedule = 'd')) %>%
  filter_ein()



# select variables that have data across multiple years
endowment <- all_sched_d %>%
    rename_with(~gsub("/Return/ReturnData/IRS990ScheduleD/", "", .)) %>%
  # contains CY or Minus
  select(fiscal_year, EIN, matches("CY|Minus", ignore.case= FALSE)) %>%
  # these are higher level variables in the nested structure, we want to be 
  # working with variables contained in these nodes
  select(-c(CYEndwmtFundGrp,
            CYMinus1YrEndwmtFundGrp,
            CYMinus2YrEndwmtFundGrp,
            CYMinus3YrEndwmtFundGrp,
            CYMinus4YrEndwmtFundGrp)) %>%
  # rename to CM* using the same formatting as we have throughout the project
  rename_with(~gsub("EndwmtFundGrp/|inus|Yr", "", .)) %>%
  mutate(across(matches("CY"), as.numeric))
  

# endowment variables that do not have data across multiple years
add_vars <- all_sched_d %>%
  select(fiscal_year, EIN, contains("end")) %>%
  select(fiscal_year, EIN, !matches("CY|Minus", ignore.case= FALSE))  %>%
  rename_with(~gsub("/Return/ReturnData/IRS990ScheduleD/", "", .)) 


  

```


```{r}

base_names <- colnames(endowment) %>% 
  gsub('CY|CYM1|CYM2|CYM3|CYM4', '', .) %>%
  unique() 

base_names <- base_names[!base_names %in% c("EIN", "fiscal_year")]


base_name <- base_names[1]




endowment_most_recent <- endowment %>%
  select(EIN, fiscal_year, contains(base_name)) %>%
  # make sure each has every fiscal years with NAs for fiscal years that are missing
   pivot_wider(names_from = fiscal_year, 
               values_from=contains(base_name)) %>%
   pivot_longer(cols = contains(base_name),
                names_to = "variable_year") %>%
   separate(variable_year, sep = "_", into = c("variable_name", "fiscal_year")) %>%
   mutate(fiscal_year = as.integer(fiscal_year)) %>%
    mutate(value_year = case_when(
     variable_name == paste0("CY", base_name) ~ fiscal_year,
     variable_name == paste0("CYM1", base_name) ~ fiscal_year -1,
     variable_name == paste0("CYM2", base_name) ~ fiscal_year -2,
     variable_name == paste0("CYM3", base_name) ~ fiscal_year -3,
     variable_name == paste0("CYM4", base_name) ~ fiscal_year -4),
     source = ifelse(grepl("CYM", variable_name), 
                     substr(variable_name, 1,4), 
                     "CY"),
     source = paste0(source, fiscal_year)) %>%
    group_by(EIN, value_year) %>%
    filter(!is.na(value)) %>%
    slice_max(n = 1, order_by = fiscal_year)%>% 
    ungroup() %>%
    mutate(variable_name = base_name,
           year = value_year,
           value,
           # assignment operator := needed when we use !! on the left side of an assigment
           name = !!base_name) %>%
  select(EIN, fiscal_year = year, source, value, name)



get_most_recent <- function(endowment_df, base_name) {
  endowment_df %>%
    select(EIN, fiscal_year, contains(base_name)) %>%
    # make sure each has every fiscal years with NAs for fiscal years that are missing
     pivot_wider(names_from = fiscal_year, 
                 values_from=contains(base_name)) %>%
     pivot_longer(cols = contains(base_name),
                  names_to = "variable_year") %>%
     separate(variable_year, sep = "_", into = c("variable_name", "fiscal_year")) %>%
     mutate(fiscal_year = as.integer(fiscal_year)) %>%
      mutate(value_year = case_when(
       variable_name == paste0("CY", base_name) ~ fiscal_year,
       variable_name == paste0("CYM1", base_name) ~ fiscal_year -1,
       variable_name == paste0("CYM2", base_name) ~ fiscal_year -2,
       variable_name == paste0("CYM3", base_name) ~ fiscal_year -3,
       variable_name == paste0("CYM4", base_name) ~ fiscal_year -4),
       source = ifelse(grepl("CYM", variable_name), 
                       substr(variable_name, 1,4), 
                       "CY"),
       source = paste0(source, fiscal_year)) %>%
          filter(!is.na(value)) %>%
      group_by(EIN, value_year) %>%
      slice_max(n = 1, order_by = fiscal_year)%>% 
      ungroup() %>%
      mutate(variable_name = base_name,
             year = value_year,
             value,
             # assignment operator := needed when we use !! on the left side of an assigment
             name = !!base_name) %>%
    select(EIN, fiscal_year = year, source, value, name)

}



endowment_recent <- map_df(base_names,
       ~get_most_recent(endowment, base_name = .x))

# endowment_recent <- endowment_recent %>% 
#   pivot_wider(names_from = name,
#               values_from = value)


endowment_recent_long <- endowment_recent %>% mutate(version = "recent") %>% select(-source)

endowment_recent_long <- endowment_recent %>%
  select(-source) %>%
  pivot_longer(-c(fiscal_year,EIN)) %>%
  mutate(version = "recent") 


end_original <- endowment %>%
  select(fiscal_year, EIN, paste0("CY", base_names)) %>%
  pivot_longer(-c(fiscal_year,EIN)) %>%
  mutate(name = gsub("CY", '', name)) %>%
  mutate(fiscal_year = as.numeric(paste(fiscal_year))) %>%
  mutate(version = "original")


endowment_recent_long %>%
  bind_rows(end_original) %>%
  # group_by(EIN, fiscal_year, name, version) %>%
  # dplyr::mutate(n = dplyr::n(), .groups = "drop") %>%  
  pivot_wider(names_from = version, values_from = value) %>%
  filter(!is.na(original)) %>%
  filter(recent != original)


  inner_join(end_original, by = c('name', 'value', 'EIN', 'fiscal_year'))


get_most_recent(endowment,base_names[2] )




endowment_most_recent <- endowment %>%
  select(EIN, fiscal_year, contains(base_name)) %>%
  # make sure each has every fiscal years with NAs for fiscal years that are missing
   pivot_wider(names_from = fiscal_year, 
               values_from=contains(base_name)) %>%
   pivot_longer(cols = contains(base_name),
                names_to = "variable_year") %>%
   separate(variable_year, sep = "_", into = c("variable_name", "fiscal_year")) %>%
   mutate(fiscal_year = as.integer(fiscal_year)) %>%
    mutate(value_year = case_when(
     variable_name == paste0("CY", base_name) ~ fiscal_year,
     variable_name == paste0("CYM1", base_name) ~ fiscal_year -1,
     variable_name == paste0("CYM2", base_name) ~ fiscal_year -2,
     variable_name == paste0("CYM3", base_name) ~ fiscal_year -3,
     variable_name == paste0("CYM4", base_name) ~ fiscal_year -4),
     source = ifelse(grepl("CYM", variable_name), 
                     substr(variable_name, 1,4), 
                     "CY"),
     source = paste0(source, fiscal_year)) %>%
    group_by(EIN, value_year) %>%
    filter(!is.na(value)) %>%
    slice_max(n = 1, order_by = fiscal_year)%>% 
    ungroup() %>%
    mutate(variable_name = base_name,
           year = value_year,
           # assignment operator := needed when we use !! on the left side of an assigment
           !!base_name := value) %>%
  rename(base_name= value) %>%
  select(EIN, fiscal_year = year, source, !!base_name)





    mutate(most_recent = value[which.max(!is.na(fiscal_year))]) %>%
  filter(EIN == "042312734") %>%
  arrange(value_year) %>% View()



    slice_max(n=1, order_by= fiscal_year) %>%
     ungroup() %>% 
    mutate(variable_name = base_name,
           year = value_year,
           # assignment operator := needed when we use !! on the left side of an assigment
           !!base_name := value) %>%
  rename(base_name= value) %>%
  select(EIN, fiscal_year = year, source, !!base_name)



end %>%
  filter(EIN == "042312734")

endowment %>%
  filter(EIN == "042312734")%>%
  select(EIN, fiscal_year, CYBeginningYearBalanceAmt)
           

endowment %>%
  select(EIN, fiscal_year, CYBeginningYearBalanceAmt)
           
           
           = ifelse(grepl("CYM", name), substr(name, 1,4), "CY"),
           year_lag = ifelse(grepl("CYM", name), substr(source, 4,4), 0),
           year_lag = as.numeric(year_lag),
           fiscal_year = as.integer(paste0(fiscal_year)))


  mutate(lag = )
   pivot_wider(names_from = variable_name, values_from = value) %>%
   mutate(fiscal_year = as.factor(as.numeric(fiscal_year)))

```






```{r,eval = FALSE}
# scratch


# get names of all schedule D variables present in any file
all_sched_d <- map(files, ~get_all_children(
  filename = .x, 
  xpath =  "//IRS990ScheduleD"))

all_sched_d <- all_sched_d %>% unlist() %>% unique()



endowment <- map_df(files, ~get_df(variables = path_to_name$path, 
                      names = path_to_name$name,
                      filename = .x))


add_vars <-c("/Return/ReturnData/IRS990ScheduleD/BoardDesignatedBalanceEOYPct",
                 "/Return/ReturnData/IRS990ScheduleD/PrmnntEndowmentBalanceEOYPct",
                 "/Return/ReturnData/IRS990ScheduleD/TermEndowmentBalanceEOYPct",
                 "/Return/ReturnData/IRS990ScheduleD/EndowmentsHeldUnrelatedOrgInd",
                 "/Return/ReturnData/IRS990ScheduleD/EndowmentsHeldRelatedOrgInd")
  
  
  
# clean paths to names
path_to_name <- tibble(path = all_sched_d) %>%
  filter(grepl("CY|CYM", path) | path %in% add_vars) %>%
  # rename to CM* using the same formatting as we have throughout the project
  mutate(name = gsub("EndwmtFundGrp/|inus|Yr", "", path),
         name = gsub('.*./', '', name))
  

```

