# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on: [push]

name: render-rmarkdown

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: True
          cache-version: 2
      - name: Download archive, extract, and run Rscript
        run: |
          wget "${{ secrets.ARCHIVE_BASE }}${{ vars.ARCHIVE_NAME }}.zip${{ secrets.ARCHIVE_SAS_QUERY_STRING }}" -O "${{ vars.ARCHIVE_NAME }}.zip"
          unzip "${{ vars.ARCHIVE_NAME }}.zip" -d ${{ vars.ARCHIVE_NAME }}
          Rscript RUN_ALL.R

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-from-rmarkdown
          path: |
            output_html
